version: '3.7'

services:
  client:
    container_name: article_client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start
    restart: always
  server:
    container_name: article_server
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 8000:8000
    command: npm run start:dev && npm run db
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: article_postgres
    image: postgres
    env_file:
      - ./server/.env
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres   
      POSTGRES_DB: nasctech
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5433:5432
    volumes:
      - /pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
networks: 
  default: 
    external: 
      name: article_app